---

- name: Playing with Ansible & Git
  connection: local
  gather_facts: false
  hosts: localhost
  tasks:
    # - name: ansible create directory example
      # file:
        # path: /tmp/devops_directory
        # state: directory
    - name: Clone a private repository into /opt.
      git:
        repo: git@github.com:shahe-islam/hello-world-reader-app.git
        version: master
        dest: ~/Developer/Ansible
        accept_hostkey: yes
        force: yes
      # ssh-agent doesn't allow key to pass through remote sudo commands.
      become: no
    - name: Run env file
      shell: ./.env
      args:
        chdir: ~/Developer/Ansible
    # - name: Run Python Script
      # script: ~/Developer/Ansible/helloWorldReaderApp/hwreaderapp.py
      # args:
        # executable: python3